version: '3'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    volumes:
      - ./chroma_db:/app/chroma_db

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - api